Add funders to a publication - API and UI
JiscSD/octopus pull request #136
Opened 2022-05-13 13:32 UTC by shaunajisc

The purpose of this PR is to create a feature which enables users to add funders to their publication. 

This PR contains the amended schema, new create and delete funder endpoints, tests, a component that handles the addition/ deletion of funders on the UI within the 'publish a publication' process and amendments to global state.

There are two new endpoints that are as follows:

- Create a funder 
Path: `POST /publications/{id}/funders`
which takes a body that looks like this: 
```javascript
{
            city: 'Manchester',
            country: 'United Kingdom',
            ror: '',
            publicationId: 'cl3465xvj0001c376ov42qbbo'
            name: 'Manchester Health and Wellbeing Service',
            link: 'https://buzzmanchester.co.uk/'
}
```
-  Delete a funder
Path: `DELETE /publications/{id}/funders/{funder}`
Which takes no body 

## Acceptance Criteria:
- Users can add many funders.
- Required fields: name, city, country_name, link, ror (optional)
- This can be populated via a ROR ID or manually.
- Once a publication is live funders cannot be edited
- Only the submitter of a publication can modify funders.

## Tests:
```
 PASS  src/components/funder/__tests__/createFunder.test.ts (10.787 s)
  create a funder
    ✓ User can add a funder to their DRAFT publication (897 ms)
    ✓ User cannot add a funder to their LIVE publication (594 ms)
    ✓ User cannot add a funder to another DRAFT publication (583 ms)
    ✓ User cannot add a funder to another LIVE publication (594 ms)
    ✓ User must send correct information to create a funder (no name) (549 ms)
    ✓ User must send correct information to create a funder (no city) (579 ms)
    ✓ User must send correct information to create a funder (no country) (583 ms)
    ✓ User must send correct information to create a funder (no link) (640 ms)
```

```
 PASS  src/components/funder/__tests__/deleteFunder.test.ts (7.883 s)
  delete a funder
    ✓ User can delete a funder from a DRAFT publication (812 ms)
    ✓ User cannot delete a funder from a DRAFT publication they are not the owner of (578 ms)
    ✓ User cannot delete a funder from a LIVE publication (538 ms)
```

## Screenshots:
![Screenshot 2022-05-13 at 14 23 19](https://user-images.githubusercontent.com/100135505/168293283-e5a3bd51-3d5a-4c42-950c-c027f60a170d.png)

![Screenshot 2022-05-13 at 14 06 04](https://user-images.githubusercontent.com/100135505/168289750-1397bad5-5971-4059-a4c5-e617d77f9882.png)

![Screenshot 2022-05-13 at 14 09 11](https://user-images.githubusercontent.com/100135505/168290248-5dd7c3f9-d174-41ef-9b45-b8ffa8a0e78c.png)

2022-05-16 14:02 UTC, AshleyRedmanJisc commented on api/serverless.yml
> +        warmup: true
Don't think this is required anymore

2022-05-16 14:03 UTC, AshleyRedmanJisc requested changes
Three small straight forward comments, but everything looks great.

2022-05-16 14:03 UTC, AshleyRedmanJisc commented on api/serverless.yml
> +        warmup: true
Don't think this is required anymore

2022-05-16 14:03 UTC, AshleyRedmanJisc commented on ui/src/components/Publication/Creation/Funders.tsx
> +    const [ror, setRor] = React.useState<string>('');
Don't think we need to specify type here

2022-05-16 15:04 UTC, AshleyRedmanJisc submitted a review, later dismissed

2022-05-16 15:15 UTC, shaunajisc commented on ui/src/components/Publication/Creation/Funders.tsx
> +            console.log(err);
Need to delete this

2022-05-17 08:35 UTC, nathan-at-jisc approved these changes
LGTM

2022-05-17 08:35 UTC, merged