OCT-661 - Updated amber API dependencies
JiscSD/octopus pull request #421
Opened 2023-06-15 08:37 UTC by Harry-Jisc

The purpose of this PR was to update the amber API dependencies. 

---

### Acceptance Criteria:

As Per [OCT-661](https://jiscdev.atlassian.net/browse/OCT-661?atlOrigin=eyJpIjoiNjUzMmRmNzUwNmNkNDU4ZTk4NWRjNDZiYzQyOTliNjIiLCJwIjoiaiJ9)

---

### Checklist:

- [x] Local manual testing conducted
- [x] Automated tests conducted

### Screenshots:

![db5411c3d8ec7db5a4e19dd548872648](https://github.com/JiscSD/octopus/assets/69204118/ab5a476b-3b21-4e0a-8e90-b286e11e3453)

2023-06-16 11:24 UTC, finlay-jisc submitted a review, later dismissed

2023-06-16 11:52 UTC, florin-holhos requested changes
Deployment fails because of that AJV issue we discussed yesterday...
<img width="1572" alt="image" src="https://github.com/JiscSD/octopus/assets/48569671/d6cfb804-89e9-441e-a55b-cd88b6a917ac">

2023-06-21 14:08 UTC, florin-holhos reviewed
- Fixed updateAffiliations schema TS errors
- replaced cuid with @paralleldrive/cuid2
- updated ajv to the latest version

2023-06-21 14:29 UTC, finlay-jisc approved these changes

2023-06-22 06:31 UTC, merged