OC-851: Explanatory hotspot for cross links
JiscSD/octopus pull request #704
Opened 2024-10-18 09:06 UTC by finlay-jisc

As a user, I should have an explanation of what cross links are and how to use them.

---

### Acceptance Criteria:

- In the suggested links area:
    - Whilst logged in, a link is present below the area title, above the list of publications, displayed via link style text reading “What is this?” and an “info” type icon pointing to the “How are related publications identified?” section of the FAQ
    - The FAQ includes a new “How are related publications identified?” section. Copy as follows: 
```
How are related publications identified?

To avoid bias, Octopus does not use any sort of algorithm to identify related publications. Instead, whilst viewing a publication that has already been published, the related publications area displays publications that have been identified by readers as being related to the one currently being viewed.
To make sure that this section contains useful links, after clicking through to a related publication, you are able to vote on whether or not you think it is in some way relevant to the one just came from. 
If you know of another publication that is relevant to the one you are viewing, you can also use the “Suggest a link” option to add it to the list.
```
---

### Checklist:

- [x] Local manual testing conducted
- [x] Automated tests added
- [x] Documentation updated

---

### Tests:

E2E
![Screenshot 2024-10-18 095537](https://github.com/user-attachments/assets/a3c9f098-d162-4281-9a14-c05392515509)

UI
![Screenshot 2024-10-18 100235](https://github.com/user-attachments/assets/47297034-e947-4a94-8da0-d45d80a9d41a)

---

### Screenshots:
![Screenshot 2024-10-18 100545](https://github.com/user-attachments/assets/b31865bb-63ad-426d-b9ae-57aafa1ff078)

2024-10-22 14:54 UTC, karmseveeratjisc requested changes
small small change to text..

2024-10-22 14:54 UTC, karmseveeratjisc commented on ui/src/pages/faq.tsx
> +            <p className="mb-2">To make sure that this section contains useful links, after clicking through to a related publication, you are able to vote on whether or not you think it is in some w
```suggestion
            <p className="mb-2">To make sure that this section contains useful links, after clicking through to a related publication, you are able to vote on whether or not you think it is in some way relevant to the one you just came from.</p>
```

2024-10-22 15:16 UTC, finlay-jisc commented on ui/src/pages/faq.tsx
> +            <p className="mb-2">To make sure that this section contains useful links, after clicking through to a related publication, you are able to vote on whether or not you think it is in some w
Thanks

2024-10-23 08:53 UTC, karmseveeratjisc approved these changes

2024-10-23 08:53 UTC, merged